# Generated by Django 3.1.7 on 2021-03-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_dynaddress'),
        ('general', '0008_about_us_mobile'),
    ]

    operations = [
    ]
